### ISSUE TITLE
Integrate NES-City Into Tutorial

### ISSUE THREAD

**Issue by alepping** [nebulastream/nebulastream-tutorial#5]
# Description
A while back, we created a simple smart city simulation [NES-City](https://github.com/nebulastream/nebulastream-smart-city-demo) that serves  three major purposes:
1. The simulated sensors of NES-City produce data streams that can be used as input to NES.
2. NES-City is interactive. Users can change its simulated IoT environment and thereby influence the data produced by its sensors (e.g. changing the time of the day or the number of patients waiting in front of hospitals).
3. NES-City provides actuation endpoints. By submitting actuation queries to NES, users can automatically influence NES-City's behavior (e.g. the number of active street lights at night can be automatically controlled by NES, based on the amount of produced and consumed energy in NES-City).

With this issue, we integrate NES-City into the nebulastream tutorial via another Docker image. 
The final goal is to provide a one-click setup for users, which allows people interested in NebulaStream, to simple visit a website, where we automatically set up NES-UI, NES and NES-City and allow users to play around with our components and experience, how NES operates in our simulated smart city scenarios.

**Comment by alepping** [comment]
Since this is first point of contact for anyone interested in NES, I have decided to first cover this issue in the NES-City repository and only when we are sure that it works 'flawlessly' there, we move the changes into this repository.
Hence, the issue is covered here for now: https://github.com/nebulastream/nebulastream-smart-city-demo/issues/55

**Comment by he-sk** [comment]
Should I close this issue, since we now have this integration?

**Comment by he-sk** [comment]
Fixed by #c2666b7
